name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    uses: ./.github/workflows/pytest.yml
    secrets: inherit

  docs:
    uses: ./.github/workflows/docs.yml
